"""Pydantic models for the agricultural entities."""

from __future__ import annotations

from smart_agri.domain.models import (
    Farm,
    Field_,
    Sensor,
    SensorReading,
    SensorStatus,
    SoilType,
)
from smart_agri.domain.operations import (
    CostCategory,
    FaultSeverity,
    FieldCost,
    FieldIndexObservation,
    Harvest,
    ImagerySource,
    InputApplication,
    InputType,
    IrrigationEvent,
    IrrigationMethod,
    Machine,
    MachineFault,
    MachineOperation,
    MachineStatus,
    MachineType,
    OperationType,
    Planting,
    PlantingStatus,
    QualityGrade,
    WaterSource,
)

__all__ = [
    "CostCategory",
    "Farm",
    "FaultSeverity",
    "FieldCost",
    "FieldIndexObservation",
    "Field_",
    "Harvest",
    "ImagerySource",
    "InputApplication",
    "InputType",
    "IrrigationEvent",
    "IrrigationMethod",
    "Machine",
    "MachineFault",
    "MachineOperation",
    "MachineStatus",
    "MachineType",
    "OperationType",
    "Planting",
    "PlantingStatus",
    "QualityGrade",
    "Sensor",
    "SensorReading",
    "SensorStatus",
    "SoilType",
    "WaterSource",
]
